# Generated by Django 5.0.6 on 2024-05-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="geom",
            new_name="locations",
        ),
    ]
