# Generated by Django 5.0.6 on 2024-05-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_rename_geom_place_locations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="locations",
            new_name="location",
        ),
    ]
