# Generated by Django 5.0.6 on 2024-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_rename_locations_place_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
